"""
MTSET_call
=============

Description
-----------
This module provides an interface to interact with the MTSET executable
from Python. It creates a subprocess for the MSET executable, loads in the
input file walls.xxx, and writes the output to the tdat.xxx data file for use
within MTSOL.

Classes
-------
MSET_call
    A class to handle the interface between Python and the MSET executable.

Examples
--------
>>> analysisName = "test_case"
>>> test = MTSET_call("test_case")
>>> execute_MTSET = test.caller()

Notes
-----
This module is designed to work with the MTSET executable. Ensure that the
executable and the input file, walls.xxx, are present in the same directory as
this Python file. When executing the file as a standalone, it uses the inputs
and calls contained within the if __name__ == "__main__" section. This part
also imports the time module to measure the time needed to perform each file
generation call. This is beneficial in runtime optimisation.

References
----------
The required input data, limitations, and structures are documented within the
MTFLOW user manual:
https://web.mit.edu/drela/Public/web/mtflow/mtflow.pdf

Versioning
------
Author: T.S. Vermeulen
Email: T.S.Vermeulen@student.tudelft.nl
Student ID: 4995309
Version: 1.2

Changelog:
- V0.5: Initial working version. Keeps fixed grid resolution as generated by
        MTSET without refining. Grid refining to be added in final version.
- V0.6: Updated documentation & type hinting. Removed dummy inputs &
        streamlined execution.
- V0.7: Now uses streamline-bunching towards the stagnation streamlines, and
        updated streamline and streamwise point spacing/counts.
- V1.0: Implemented waiting loop until statefile has been generated. Class now
        automatically deletes statefile if it already existed at start of
        execution. Added stdinwrite function to clean up writing to subprocess.
- V1.1: Improved waiting loop for statefile generation to use exponential
        backoff in the time.sleep calls. Updated documentation.
- V1.2: Improved formatting and documentation
"""

# Import standard libraries
import subprocess, time
from pathlib import Path


class MTSET_call:
    """
    Class to handle the interface between MTSET and Python
    """

    def __init__(self,
                 analysis_name: str,
                 grid_e_coeff: float = None,
                 grid_x_coeff: float = None,
                 streamwise_points: int = None,
                 ) -> None:
        """
                 Initialize MTSET_call for a specific analysis, configuring grid parameters and locating required Submodels files.
                 
                 Parameters:
                     analysis_name (str): Analysis case identifier used to name input/output files.
                     grid_e_coeff (float, optional): Exponent coefficient for airfoil-side grid clustering; defaults to 0.8 when None.
                     grid_x_coeff (float, optional): X-spacing factor controlling grid rectangularity; defaults to 0.8 when None.
                     streamwise_points (int, optional): Number of streamwise grid points; defaults to 200 when None or when provided value is <= 141.
                 
                 Raises:
                     FileNotFoundError: If the MTSET executable (Submodels/mtset.exe) cannot be found.
                 """

        self.analysis_name = analysis_name

        # Grid definition parameters need to either take the user-defined
        # input or the default inputs
        self.grid_e_coeff = grid_e_coeff if grid_e_coeff is not None else 0.8
        self.grid_x_coeff = grid_x_coeff if grid_x_coeff is not None else 0.8
        self.streamwise_points = streamwise_points if (streamwise_points is not None and streamwise_points > 141) else 200

        # Define key paths/directories
        self.parent_dir = Path(__file__).resolve().parent.parent
        self.submodels_path = self.parent_dir / "Submodels"

        # Define constant filepath for the MTSET executable
        self.process_path = self.submodels_path / 'mtset.exe'
        if not self.process_path.exists():
            raise FileNotFoundError(f"MTSET executable not found at {self.process_path}")

        # Define filepath for the statefile
        self.fpath = self.submodels_path / f'tdat.{self.analysis_name}'

        # Define filepath for walls.xxx
        self.wallspath = self.submodels_path / f"walls.{self.analysis_name}"


    def StdinWrite(self,
                   command: str) -> None:
        """
                   Write a command string to the MTSET subprocess stdin.
                   
                   Parameters:
                       command (str): Text command to send to MTSET; a newline is appended and the stdin is flushed.
                   """

        self.process.stdin.write(f"{command} \n")
        self.process.stdin.flush()


    def GenerateProcess(self) -> None:
        """
        Create and start the MTSET subprocess and assign it to `self.process`.
        
        Starts the MTSET executable using the instance's configured `process_path` and `analysis_name`, with stdin/stdout connected for interaction. Raises `OSError` if the subprocess fails to start.
        """

        # Generate subprocess
        self.process = subprocess.Popen([self.process_path, self.analysis_name],
                                 stdin=subprocess.PIPE,
                                 stdout=subprocess.PIPE,
                                 stderr=subprocess.DEVNULL,
                                 text=True,
                                 bufsize=1,
                                 )

        # Check if subprocess is started successfully
        if self.process.poll() is not None:
            raise OSError("Error starting MTSET") from None


    def WaitForMainMenu(self) -> list[str]:
        """
        Wait until the MTSET subprocess returns to its main menu and collect its output lines.
        
        Returns:
            interface_output (list[str]): Lines read from the MTSET subprocess stdout up to the main-menu marker (`Q uit` at line start) or until the process exits.
        """

        interface_output = []
        while True:
            next_line = self.process.stdout.readline()  # Collect output in list
            interface_output.append(next_line)
            if next_line == "" and self.process.poll() is not None:
               # Handle (unexpected) quitting of program
               break
            if next_line.strip().startswith('Q uit'):
               # Stop collecting once end of MTSET menu is reached
               break

        return interface_output


    def GridGenerator(self) -> None:
        """
        Initialize the MTSET grid for this analysis by loading the walls file, determining element count, accepting default spacings, and applying grid modification parameters.
        
        Reads self.wallspath to determine how many elements MTSET should load, sends the necessary stdin commands to accept spacing defaults for each element, enters the grid modification menu to configure streamline bunching, streamline count, airfoil-side exponent, x-spacing factor, number of streamwise points, and the quasi-normal toggle, then exits the modification and spacing routines.
        """

        # Load the walls.xxx file and count number of elements to be loaded
        # The second(+) elements are preceded by line containing [999. 999.],
        # which can be used to count the number of elements to be loaded in
        # by MTSET
        element_count = 1  # There is a minimum of 1 element present
        with open(self.wallspath, 'r') as file:
            for index, line in enumerate(file):
                if index < 2:
                    # Skip the first two lines, which contain the analysis name
                    # and grid size.
                    continue
                numbers = map(float, line.split())
                # New element identifier contains 2x 999.
                # so divide the count by 2
                element_count += sum(1 for num in numbers if num == 999.) // 2

        #Accept the default spacing ratios for each of the elements loaded in
        for _ in range(element_count):
            self.StdinWrite("")  # Send return command to MTSET

        # Exit grid spacing definition routine
        self.StdinWrite("\n")

        # Wait for MTSET to be in the main menu before modifying the grid
        self.WaitForMainMenu()

        # Enter grid modification menu and set grid parameters
        self.StdinWrite("m")

        # Enable streamline bunching towards stagnation lines for better
        # resolution of near-element flowfield
        self.StdinWrite("j 1")

        # Use increased number of streamlines for increased resolution
        self.StdinWrite("s 45")

        # Set exponent for number of airfoil side points. The number of point
        # is then equal to e * N
        self.StdinWrite(f"e {self.grid_e_coeff}")

        # Set x spacing factor. Lower values yield a more "rounded" grid
        self.StdinWrite(f"x {self.grid_x_coeff}")

        # Set the number of streamwise points
        self.StdinWrite(f"n {self.streamwise_points}")

        # Toggle quasi-normal lines fixed in x (This is only used when there
        # is no duct, i.e. an open rotor/propeller. When there is a duct
        # present, this option is disabled, so the input has no effect)
        self.StdinWrite("Q")

        # Exit grid modification menu
        self.StdinWrite("")

        #Accept the default spacing ratios for each of the elements loaded in
        for _ in range(element_count):
            self.StdinWrite("")

        # Exit grid spacing definition routine
        self.StdinWrite("")


    def GridSmoothing(self) -> None:
        """
        Perform elliptic grid smoothing on the current grid until convergence or a maximum of 30 passes.
        
        Issues the elliptic smoothing command repeatedly and reads MTSET output; stops early when the line following the final-pass marker 'Pass          10' does not contain 'Dmax', indicating no further smoothing is required.
        """

        # Control smoothing process, including detection when further
        # smoothing is no longer needed
        smoothing_pass = 0
        while smoothing_pass < 30:
            self.StdinWrite("e")  # Execute elliptic smoothing continue command

            # Collect console output from MTSET, stopping when the end of
            # the menu is reached
            interface_output = self.WaitForMainMenu()
            smoothing_pass += 1

            # Find the index of 'Pass 10' (i.e. the final pass of the
            # smoothing process). Checks from the back of the list
            pass_10_index = next((i for i, s
                                  in reversed(list(enumerate(interface_output)))
                                  if 'Pass          10' in s), -1)

            if "Dmax" not in interface_output[pass_10_index + 1]:
                # Check the row following Pass 10 to determine convergence
                break


    def FileGenerator(self) -> None:
        """
        Write MTSET's tdat.<analysis_name> output file and ensure the MTSET process terminates.
        
        This issues the MTSET write command to produce the binary tdat file used as a starting solution for downstream analyses, then waits up to 10 seconds for the MTSET subprocess to exit and forcefully kills it if it remains running.
        """

        # Create tdat.xxx file
        # Note that MTSET automatically closes after writing the tdat file!
        self.StdinWrite("w")

        # Check that MTSET has closed successfully. If not,
        # forcefully closes MTSET
        if self.process.poll() is None:
            try:
                self.process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self.process.kill()


    def caller(self) -> None:
        """
        Orchestrates MTSET invocations to produce the tdat.{analysis_name} grid output file.
        
        This removes an existing tdat output (if present), starts the MTSET subprocess, runs grid generation and smoothing, triggers file writing, and waits (up to 10 seconds) for the resulting tdat.{analysis_name} file to appear. Requires that the input walls.{analysis_name} file already exists; creates or overwrites the tdat.{analysis_name} file as a side effect.
        """

        # Delete the tdat file, if it already existed.
        if self.fpath.exists():
            self.fpath.unlink(missing_ok=True)

        # Create subprocess for the MTSET tool
        self.GenerateProcess()

        # Initialise the numerical grid
        self.GridGenerator()

        # Perform elliptical grid smoothing
        self.GridSmoothing()

        # Generate files
        self.FileGenerator()

        # Check that the tdat file writing was successful.
        # If the file was not written yet, use an exponential backoff to
        # avoid unneccesary high workload on thread.
        timeout = 10  # s - max wait time in which file should be generated
        start_time = time.monotonic()
        backoff = 0.01  # Initial time step
        max_backoff = 0.5  # Maximum time step
        elapsed = 0  # Intialise elapsed time to zero
        while elapsed < timeout:
            if self.fpath.exists():
                # If file exists, break out of the while loop.
                break
            time.sleep(backoff)
            # Adjust the backoff based on remaining time to avoid
            # overshooting the timeout
            backoff = min(max_backoff, backoff * 2)
            elapsed = time.monotonic() - start_time


if __name__ == "__main__":
    start_time = time.time()
    analysisName = "test_case"
    test = MTSET_call(analysisName)
    execute_MTSET = test.caller()
    end_time = time.time()

    print(f"Execution of MTSET_call({analysisName}).caller() took {end_time - start_time} seconds")