"""
MTSOL_call
=============

Description
-----------
This module provides an interface to interact with the MTSOL executable
from Python. It creates a subprocess for the MTSOL executable, executes an
inviscid, and viscid if desired, solve, and writes the output data to the
statefile and the forces.xxx output file.

Classes
-------
ExitFlag
    An Enum class with exit flags for the MTSOL interface
MTSOL_call
    A class to handle the interface between Python and the MTSOL executable.

Examples
--------
>>> analysisName = "test_case"
>>> oper = {"Inlet_Mach": 0.25,
>>>         "Inlet_Reynolds": 5.000E6,
>>>         "N_crit": 9,
>>>         }
>>> test = MTSOL_call(oper, analysisName).caller(run_viscous=True)

Notes
-----
This module is designed to work with the MTSOL executable. Ensure that the
executable and the input state file, tdat.xxx, are present in the same
directory as this Python file. When executing the file as a standalone, it uses
the inputs and calls contained within the if __name__ == "__main__" section.
This part also imports the time module to measure the time needed to perform
each file generation call. This is beneficial in runtime optimization.

References
----------
The required input data, limitations, and structures are documented within the
MTFLOW user manual:
https://web.mit.edu/drela/Public/web/mtflow/mtflow.pdf

Versioning
------
Author: T.S. Vermeulen
Email: T.S.Vermeulen@tudelft.nl
Version: 2.0.5

Changelog:
- V0.0:   File created with empty class as placeholder.
- V0.9:   Minimum Working Example. Lacks crash handling and pressure ratio
          definition.
- V0.9.5: Cleaned up inputs, removing file_path and changing it to a constant.
- V1.0:   With implemented choking handling, pressure ratio definition is no
          longer needed. Added choking exit flag. Cleaned up/updated
          HandleExitFlag() method. Added critical amplification factor as input.
- V1.1:   Added file processing check to ensure that the forces file is copied
          before it is deleted. Added a check to ensure that the MTSOL
          executable is present in the same directory as this Python file.
- V1.2:   Added watchdog to check if the forces file is created before
          copying it.
- V1.3:   Added crash handling for the inviscid solve. Added a function to
          set all values to zero in case of a crash during the inviscid solve.
          Added a function to handle non-convergence by averaging over the last
          self.SAMPLE_SIZE iterations. Added a function to handle the exit flag
          of the solver execution. Added a function to handle the convergence
          of individual surfaces in case of a crash during the viscous solve.
- V1.4:   Full rework of FileCreatedHandling(). Revamped file processing.
          Cleaned up imports. Removed shell=True from process initialisation.
          Switched to pathlib for path handling. Revamped individual surface
          convergence.
- V1.4.1: Removed iter_count from outputs.
- V1.5:   Implemented efficiency check to verify inviscid solution is a physical
          result. This enables skipping of viscous solve for such cases, which
          can significantly speed up computations in batch analyses.
- V2.0:   Changed non-convergence handling to use console-based approach rather
          than file-based for significantly improved performance. General
          refactoring for improved performance. Removed NumPy dependency.
- V2.0.5: Replaced empty output generation with reading of default zeroed output
          for performance. Minor QoL improvements throughout. 
"""

# Import standard libraries
import subprocess, time, queue, threading, sys
from pathlib import Path
from enum import Enum
from typing import Any

# Import custom libraries
from output_handling import output_processing # type: ignore


class ExitFlag(Enum):
    """
    Enum class to define the exit flags for the MTSOL solver.

    The exit flags are used to determine the status of the solver execution.

    Attributes
    ----------
    SUCCESS : int
        Successful completion of the solver execution.
    CRASH : int
        MTSOL crash
    NON_CONVERGENCE : int
        Non-convergence, to be handled by the HandleNonConvergence function.
    NOT_PERFORMED : int
        Not performed, with no iterations executed or outputs generated.
    COMPLETED : int
        Finished the iteration/operation, but not converged.
    CHOKING : int
        Choking occurs somewhere in the solution, indicated by the 'QSHIFT'
        message in the MTSOL console output.
    """

    SUCCESS = -1
    CRASH = 0
    NON_CONVERGENCE = 1
    NOT_PERFORMED = 2
    COMPLETED = 3
    CHOKING = 4


class OutputType(Enum):
    """
    Enum class to define the output types to be generated by MTSOL
    """

    FORCES_ONLY = 0
    ALL_FILES = 1


class CompletionType(Enum):
    """
    Enum class to define the completion type to be checked for in MTSOL.
    """

    ITERATION = 1
    OUTPUT = 2
    PARAM_CHANGE = 3
    VISCOUS_TOGGLE = 4


class MTSOL_call:
    """
    Class to handle the interface between MTSOL and Python
    """

    # Define file templates as constants
    FILE_TEMPLATES = {'forces': "forces.{}",
                      'flowfield': "flowfield.{}",
                      'boundary_layer': "boundary_layer.{}"}


    def __init__(self,
                 operating_conditions: dict[str, float],
                 analysis_name: str,
                 ) -> None:
        """
        Initialize the MTSOL_call class.

        This method sets up the initial state of the class.

        Parameters
        ----------
        - operating_conditions : dict[str, float]
            A dictionary containing the operating conditions for the MTSOL
            analysis. The dictionary needs to contain:
                - Inlet_Mach: the inlet Mach number
                - Inlet_Reynolds: the inlet Reynolds number, calculated using
                                  Lref=fan diameter
                - N_crit: the critical amplification factor
        - analysis_name : str
            A string of the analysis name.

        Returns
        -------
        None
        """

        self.operating_conditions = operating_conditions
        self.analysis_name = analysis_name

        # Define constants for the class
        self.ITER_STEP_SIZE = 2  # Iteration step size in MTSOL
        self.SAMPLE_SIZE = 10  # Sample size for non-convergence handling
        self.ITER_LIMIT_INVISC = 50  # Maximum number of inviscid iterations
        self.ITER_LIMIT_VISC = 50  # Maximum number of viscous iterations

        # Define key paths/directories
        self.submodels_path = Path(__file__).resolve().parent

        # Define filepath of MTSOL as being in the same folder as
        # this Python file
        if sys.platform == "linux":
            self.fpath = self.submodels_path / 'mtsol'
        else:
            self.fpath = self.submodels_path / 'mtsol.exe'
        if not self.fpath.exists():
            raise FileNotFoundError("MTSOL executable not found at {}".format(self.fpath))

        # Define filepaths
        self.filepaths = {'forces': self.submodels_path / \
                          self.FILE_TEMPLATES['forces'].format(self.analysis_name),
                          'flowfield': self.submodels_path / \
                          self.FILE_TEMPLATES['flowfield'].format(self.analysis_name),
                          'boundary_layer': self.submodels_path / \
                          self.FILE_TEMPLATES['boundary_layer'].format(self.analysis_name)}

        # Define output processing class instance
        self.output_processing_class = output_processing()


    def StdinWrite(self,
                   command: str) -> None:
        """
        Simple function to write commands to the subprocess stdin in order to
        pass commands to MTSOL

        Parameters
        ----------
        - command : str
            The text-based command to pass to MTSOL

        Returns
        -------
        None
        """

        self.process.stdin.write(f"{command} \n")
        self.process.stdin.flush()


    def GenerateProcess(self) -> None:
        """
        Create MTSOL subprocess

        Requires that the executable, mtsol.exe, and the input file, tdat.xxx
        are present in the same directory as this Python file.

        Parameters
        ----------
        None

        Returns
        -------
        None
        """

        # Add a shutdown event to signal thread termination or
        # reset the existing one
        if not hasattr(self, "shutdown_event"):
            self.shutdown_event = threading.Event()
        else:
            self.shutdown_event.clear()

        # Stop any orphaned reader threads if they exist before starting
        # the new subprocess
        if getattr(self, "reader", None) and self.reader.is_alive():
            if getattr(self, "process", None) and self.process.stdout:
                self.process.stdout.close()
            # Signal the thread to stop
            self.shutdown_event.set()
            self.reader.join(timeout=5)
            self.reader = None

        # Generate the subprocess and write it to self
        # First check if the process already exists. If it does, close it
        # before starting the new subprocess
        if getattr(self, "process", None) and self.process.poll() is None:
            try:
                self.process.terminate()
                self.process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self.process.kill()
                self.process.wait(timeout=10)  # Wait for termination

        self.process = subprocess.Popen([self.fpath, self.analysis_name],
                                        stdin=subprocess.PIPE,
                                        stdout=subprocess.PIPE,
                                        stderr=subprocess.DEVNULL,
                                        text=True,
                                        bufsize=1,
                                        cwd=self.submodels_path
                                        )

        # Initialize output reader thread.
        # Uses an unbounded queue to prevent deadlocks if output
        # accumulates faster than processed
        self.output_queue = queue.Queue()

        def output_reader(out, q) -> None:
            """ Helper function to read the output on a separate thread """
            try:
                while not getattr(self,
                                  "shutdown_event",
                                  threading.Event()).is_set():
                    if self.process.poll() is not None:
                        # Check if the process is still running before
                        # reading stdout.
                        break
                    line = out.readline()
                    if not line:
                        break
                    q.put(line)
            except ValueError:
                # Catch value errors separately to avoid spamming console out
                # with "I/O operation on closed file" errors during MTSOl
                # crashes/restarts
                pass
            except Exception as e:
                print(e)

        self.reader = threading.Thread(target=output_reader,
                                       args=(self.process.stdout,
                                             self.output_queue))
        self.reader.daemon = True

        # Start the reader thread
        self.reader.start()

        # Check if subprocess is started successfully
        if self.process.poll() is not None:
            raise ImportError(f"MTSOL or tdat.{self.analysis_name} not found in {self.fpath}") from None


    def SetOperConditions(self) -> None:
        """
        Set the operating conditions for the MTSOL analysis.

        Sets the inlet Mach number, and sets the Reynolds number equal to zero
        to ensure an inviscid case is obtained.

        Parameters
        ----------
        None

        Returns
        -------
        None
        """

        # Enter the Modify solution parameters menu
        self.StdinWrite("m")

        # Write inlet Mach number
        self.StdinWrite(f"M {self.operating_conditions['Inlet_Mach']}")

        # Wait for completion of processing operating condition change
        self.WaitForCompletion(completion_type=CompletionType.PARAM_CHANGE)

        # Set the Reynolds number to 0 to ensure an inviscid solve
        # is performed initially
        self.StdinWrite("R 0")

        # Wait for completion of processing operating condition change
        self.WaitForCompletion(completion_type=CompletionType.PARAM_CHANGE)

        # Set momentum/entropy conservation Smom flag
        self.StdinWrite("S 4")

        # Wait for completion of processing operating condition change
        self.WaitForCompletion(completion_type=CompletionType.PARAM_CHANGE)

        # Exit the modify solution parameters menu
        self.StdinWrite("")


    def ToggleViscous(self) -> None:
        """
        Toggle the viscous setting for all surfaces by setting the inlet
        Reynolds number. Note that the Reynolds number must be defined using
        the MTFLOW reference length LREF.

        Parameters
        ----------
        None

        Returns
        -------
        None
        """

        # Enter the Modify solution parameters menu
        self.StdinWrite("m")

        # Set critical amplification factor to N=9 rather than the default N=7
        self.StdinWrite(f"N {self.operating_conditions['N_crit']}")

        # Wait for completion of processing operating condition change
        self.WaitForCompletion(completion_type=CompletionType.PARAM_CHANGE)

        # Set the viscous Reynolds number, calculated using the length self.LREF
        self.StdinWrite(f"R {self.operating_conditions['Inlet_Reynolds']}")

        # Wait for completion of processing operating condition change
        self.WaitForCompletion(completion_type=CompletionType.PARAM_CHANGE)

        # Exit the Modify solution parameters menu
        self.StdinWrite("")


    def SetViscous(self,
                   surface_ID: list[int] | int,
                   mode: str = "enable"
                   ) -> None:
        """
        Set the viscous toggle for the given surface identifier(s).

        Parameters
        ----------
        - surface_ID : list[int] | int
            IDs of the surface which are to be toggled. For a ducted fan,
            the ID should be either 1, 3, or 4.
        - mode : str, optional
            Optional string to determine which toggling mode to use:
            enable or disable.

        Returns
        -------
        None
        """

        if mode == "enable":
            lookfor_flag = ExitFlag.COMPLETED
        elif mode == "disable":
            lookfor_flag = ExitFlag.SUCCESS
        else:
            raise ValueError(f"Unknown mode in SetViscous: {mode}")

        # Input validation to format surface_ID into a list if a
        # pure integer is provided
        if isinstance(surface_ID, int):
            surface_ID = [surface_ID]

        # Enter the Modify solution parameters menu
        self.StdinWrite("m")
        self.WaitForCompletion(completion_type=CompletionType.PARAM_CHANGE)

        # Toggle the given surfaces to enable their viscous setting only
        # if the surface was disabled
        for ID in surface_ID:
            # First check the current state of the surface
            flag = self.WaitForCompletion(completion_type=CompletionType.VISCOUS_TOGGLE,
                                          surface_ID=ID)
            while flag == lookfor_flag:
                self.StdinWrite(f"V{ID}")
                flag = self.WaitForCompletion(completion_type=CompletionType.VISCOUS_TOGGLE,
                                              surface_ID=ID)
                if flag != lookfor_flag:
                    break
        # Exit the Modify solution parameters menu
        self.StdinWrite("")


    def WaitForCompletion(self,
                          completion_type: CompletionType = CompletionType.ITERATION,
                          output_file: str = None,
                          surface_ID: int = None,
                          ) -> ExitFlag:
        """
        Monitor the console output to verify the completion of a command.

        Parameters
        ----------
        - completion_type : CompletionType, optional
            A CompletionType enum to determine what to check for. Default value
            is CompletionType.ITERATION
        - output_file : str, optional
            A string of the output file for which the completion is to be
            monitored. Either 'forces', 'flowfield', or 'boundary_layer'.
            Note that the file extension (i.e. casename), should not be
            included!
        - surface_ID : int, optional
            An integer of the surface which is to be inspected.

        Returns
        -------
        - exit_flag : ExitFlag
            Exit flag indicating the status of the solver execution.
        """

        # Define an adaptive timeout to limit CPU usage
        def adaptive_timeout(delta_t: float) -> float:
            return min(0.025 * (1 + int((delta_t) // 5)), 0.25)

        # Check the console output to ensure that commands are completed
        timer_start = time.monotonic()
        time_out = 45  # seconds
        dt = 0.  # Initialize delta time
        while dt <= time_out:
            # First check if the subprocess has terminated to ensure
            # fail fast if this is the case
            dt = time.monotonic() - timer_start
            if self.process.poll() is not None:
                return ExitFlag.CRASH

            # Read the output from the output thread
            try:
                line = self.output_queue.get(timeout=adaptive_timeout(dt))
            except queue.Empty:
                if self.process.poll() is not None:
                    return ExitFlag.CRASH
                time.sleep(adaptive_timeout(dt))
                continue

            # Once iteration is complete, return the completed exit flag
            if line.startswith(' =') and \
                completion_type == CompletionType.ITERATION:
                return ExitFlag.COMPLETED

            # Once the iteration is converged, return the converged exit flag
            elif 'Converged' in line and \
                completion_type == CompletionType.ITERATION:
                return ExitFlag.SUCCESS

            # If choking occurs, return the exit flag to choking
            elif ' *** QSHIFT: Mass flow or Pexit must be a DOF!' in line and \
                completion_type == CompletionType.ITERATION:
                return ExitFlag.CHOKING

            # Once the solution is written to the state file, or the
            # forces/flowfield file is written, return the completed exit flag
            # The succesful forces/flowfield writing can be detected from the
            # prompt to overwrite the file or to enter a filename
            elif ('Solution written to state file' in line
                  or line.startswith((' File exists.  Overwrite?  Y',
                                      'Enter filename'))) and \
                                        completion_type == CompletionType.OUTPUT:
                if output_file is not None:
                    max_wait_time = 10  # Maximum wait time in seconds
                    # Wait for the file creation to be finished
                    target_path = self.submodels_path / \
                        self.FILE_TEMPLATES[output_file].format(self.analysis_name)
                    start_time = time.monotonic()
                    elapsed_time = 0.
                    while not target_path.exists() and \
                        elapsed_time <= max_wait_time:
                        time.sleep(adaptive_timeout(elapsed_time))
                        elapsed_time = time.monotonic() - start_time

                return ExitFlag.COMPLETED

            # When changing the operating conditions,
            # check for the end of the modify parameters menu
            elif line.startswith(' ----') and \
                completion_type == CompletionType.PARAM_CHANGE:
                return ExitFlag.COMPLETED

            # When toggling viscous surfaces,
            # check for the star at the corresponding line:
            elif line.startswith(' T{} *'.format(surface_ID)) and \
                  completion_type == CompletionType.VISCOUS_TOGGLE:
                return ExitFlag.SUCCESS
            elif line.startswith(' T{}    '.format(surface_ID)) and \
                completion_type == CompletionType.VISCOUS_TOGGLE:
                return ExitFlag.COMPLETED

            # If the solver crashes, return the crash exit flag
            # A crash can be detectede either by the MTSOL subprocess exiting,
            # or neg. temp. lines in the console output
            elif self.process.poll() is not None or line.startswith(' *** Neg. temp.'):
                return ExitFlag.CRASH

        # If timer ran out while waiting for completion, assume the solver
        # has hung
        return ExitFlag.NON_CONVERGENCE


    def WriteStateFile(self) -> None:
        """
        Writes the current solution to the state file tdat.analysis_name.

        Parameters
        ----------

        Returns
        -------
        None
        """

        # Update the solution state file
        self.StdinWrite("W")

        # Check if the solution state file is written successfully
        self.WaitForCompletion(completion_type=CompletionType.OUTPUT)


    def GenerateSolverOutput(self,
                             output_type: OutputType = OutputType.FORCES_ONLY) -> None:
        """
        Generate all outputs for the current analysis.
        If a viscous analysis was performed, the boundary layer data is also
        dumped to the corresponding file. Requires that MTSOL is in the main
        menu when starting this function.

        Parameters
        ----------
        - output_type : OutputType
            An enum to determine which outputs need to be generated:
                - OutputType.FORCES_ONLY: Generate only the forces data.
                                          (default)
                - OutputType.ALL_FILES: Generate all outputs (forces, flowfield,
                                        boundary_layer)

        Returns
        -------
        None
        """

        # First check if MTSOL is still running.
        # If MTSOl has crashed, restart MTSOL based on the last saved statefile
        if getattr(self, "process", None) and self.process.poll() is not None:
            self.GenerateProcess()

        # Handle the condition where only the forces data is to be returned
        # This is the default, and always used, as the forces data list is
        # required for the non-convergence handling
        self.StdinWrite("F")
        self.StdinWrite("")  # Empty filename to dump to console

        # Read the console output until the forces data is fully processed
        timer_start = time.monotonic()
        time_out = 45  # seconds
        forces_output = []  # Initialise empty list to store the output lines
        started_reading = False  # Boolean flag to indicate start of output
        while (time.monotonic() - timer_start) <= time_out:
            # First check if the subprocess has terminated to ensure fail fast
            # if this is the case
            if self.process.poll() is not None:
                # If the solver crashes while generating the outputs,
                # wipe the stored results.
                self.forces_data = None
                return

            # Read the output from the output thread
            try:
                adaptive_timeout = min(0.025 * (1 + int((time.monotonic() - timer_start) // 5)), 0.25)
                line = self.output_queue.get(timeout=adaptive_timeout)
            except queue.Empty:
                if self.process.poll() is not None:
                    # If the solver crashes while reading the outputs, wipe the
                    # stored results.
                    self.forces_data = None
                    return
                time.sleep(0.01)
                line = ""
                continue

            if line.startswith('  Total power'):
                started_reading = True
                forces_output.append(line)
            elif line.startswith('                    CPK1'):
                # End of the usable section of the forces output,
                # so break the loop
                started_reading = False
                forces_output.append(line)
                break
            elif started_reading:
                forces_output.append(line)

        self.forces_data = forces_output
        self.forces_data_dict = self.output_processing_class.GetAllVariables(forces_data=forces_output)

        # Handle the case where all outputs are to be handled
        if output_type == OutputType.ALL_FILES:
            self.StdinWrite("F")
            self.StdinWrite(self.FILE_TEMPLATES['forces'].format(self.analysis_name))
            if self.filepaths["forces"].exists():
                self.StdinWrite("Y")  # Overwrite existing file

            # Check if the forces file is written successfully
            self.WaitForCompletion(completion_type=CompletionType.OUTPUT,
                                output_file='forces')

            # Dump the flowfield data
            self.StdinWrite("D")
            self.StdinWrite(self.FILE_TEMPLATES['flowfield'].format(self.analysis_name))
            if self.filepaths["flowfield"].exists():
                self.StdinWrite("Y")  # Overwrite existing file

            # Check if the flowfield file is written successfully
            self.WaitForCompletion(completion_type=CompletionType.OUTPUT,
                                output_file='flowfield')

            # Dump the boundary layer data
            self.StdinWrite("B")
            self.StdinWrite(self.FILE_TEMPLATES['boundary_layer'].format(self.analysis_name))
            if self.filepaths["boundary_layer"].exists():
                self.StdinWrite("Y")  # Overwrite existing file

            # Check if the boundary layer file is written successfully
            self.WaitForCompletion(completion_type=CompletionType.OUTPUT,
                                   output_file='boundary_layer')


    def ExecuteSolver(self, 
                      iter_limit: int) -> ExitFlag:
        """
        Execute the MTSOL solver for the current analysis.

        Parameters
        ----------
        - iter_limit : int
            The maximum number of iterations to perform before declaring
            non-convergence.

        Returns
        -------
        - exit_flag : ExitFlag
            Exit flag indicating the status of the solver execution.
        """

        # Initialize iteration count and exit flag
        iter_counter = 0
        exit_flag = ExitFlag.NOT_PERFORMED

        # Keep converging until the iteration count exceeds the limit
        while (iter_counter < iter_limit) and \
            (exit_flag not in (ExitFlag.SUCCESS,
                               ExitFlag.CHOKING,
                               ExitFlag.CRASH)):
            #Execute next iteration(s)
            self.StdinWrite(f"x {self.ITER_STEP_SIZE}")

            # Check the exit flag to see if the solution has converged
            # If the solution has converged, break out of the iteration loop
            exit_flag = self.WaitForCompletion(completion_type=CompletionType.ITERATION)

            if exit_flag != ExitFlag.CRASH:
                # Increase the iteration counter for all non-crash states
                iter_counter += self.ITER_STEP_SIZE

            # Break on terminal states
            if exit_flag in (ExitFlag.SUCCESS, ExitFlag.CHOKING, ExitFlag.CRASH):
                break

        # If the solver has not converged within self.ITER_LIMIT iterations,
        # set the exit flag to non-convergence
        if exit_flag not in (ExitFlag.SUCCESS, ExitFlag.CHOKING, ExitFlag.CRASH):
            exit_flag = ExitFlag.NON_CONVERGENCE

        # Return the exit flag
        return exit_flag


    def HandleNonConvergence(self) -> None:
        """
        Average over the last self.SAMPLE_SIZE iterations to determine the
        integral flowfield variables.

        This method performs the following steps for each of the iterations
        considered:
            - Executes an iteration
            - Generates the forces output data from the console output and write
              it to a list
        After all iterations are performed, the average of the forces data is
        computed and written to the forces_data_dict attribute.

        Parameters
        ----------
        None

        Returns
        -------
        None
        """

        # Initialize iteration counter and list to store forces data
        iter_counter = 0
        forces_outputs = []

        # Keep looping until iter_count exceeds the target value for number of
        # iterations to average
        while iter_counter < self.SAMPLE_SIZE:
            # First check if subprocess is still alive. If the solver has
            # crashed, restart MTSOL and break the loop.
            if self.process.poll() is not None:
                self.forces_data_dict = self.output_processing_class.GetAllVariables()
                return

            #Execute iteration
            self.StdinWrite("x1")

            if self.WaitForCompletion(completion_type=CompletionType.ITERATION) == ExitFlag.CRASH:
                # If the iteration crashes, set zeroed outputs and return
                self.forces_data_dict = self.output_processing_class.GetAllVariables()
                return

            # Generate solver outputs
            self.GenerateSolverOutput(output_type=OutputType.FORCES_ONLY)
            if self.forces_data is not None:
                forces_outputs.append(self.forces_data)

            # Increase iteration counter by step size
            iter_counter += 1

        # Convert all output lists into dictionaries
        forces_outputs_dicts = [self.output_processing_class.GetAllVariables(forces_data=output)
                                for output in forces_outputs]

        # Define helper functions to compute average from list of dictionaries
        def _accumulate(sum_dict: dict[str, Any],
                        count_dict: dict[str, Any],
                        input_dict: dict[str, Any]) -> None:
            """
            Populate a sum and count dictionary from the input dictionary
            recursively for averaging.

            Parameters
            ----------
            - sum_dict : dict[str, Any]
                Dictionary to store the accumulated sums.
            - count_dict : dict[str, Any]
                Dictionary to store the counts of values.
            - input_dict : dict[str, Any]
                Input dictionary to accumulate values from.

            Returns
            -------
            None
            """

            for key, value in input_dict.items():
                if isinstance(value, dict):
                    if key not in sum_dict:
                        sum_dict[key] = {}
                        count_dict[key] = {}
                    _accumulate(sum_dict[key], count_dict[key], value)
                else:
                    sum_dict[key] = sum_dict.get(key, 0.0) + float(value)
                    count_dict[key] = count_dict.get(key, 0) + 1


        def _compute_average(sum_dict: dict[str, Any],
                             count_dict: dict[str, Any]) -> dict[str, float]:
            """
            Create an average dictionary from the sum and count dictionaries.

            Parameters
            ----------
            - sum_dict : dict[str, Any]
                Dictionary containing the accumulated sums.
            - count_dict : dict[str, Any]
                Dictionary containing the counts of values.

            Returns
            -------
            - avg_dict : dict[str, float]
                Dictionary containing the computed averages.
            """

            avg_dict = {}
            for key in sum_dict:
                if isinstance(sum_dict[key], dict):
                    avg_dict[key] = _compute_average(sum_dict[key],
                                                     count_dict[key])
                else:
                    avg_dict[key] = sum_dict[key] / count_dict[key]
            return avg_dict

        # Now compute the average dictionary and write the averaged values to
        # the forces dictionary attribute
        sums = {}
        counts = {}
        for output in forces_outputs_dicts:
            _accumulate(sums, counts, output)

        # Only write the averages if at least one valid output was found
        if sums:  # Check if we have any data to average
            self.forces_data_dict = _compute_average(sums, counts)
        else:
            # Preserve the existing structure or initialize with zeros
            if not hasattr(self, 'forces_data_dict') or not self.forces_data_dict:
                self.forces_data_dict = self.output_processing_class.GetAllVariables()


    def CheckInviscidOutput(self) -> bool:
        """
        Check the efficiency of the invisicid output.

        When interpolatation errors occur in the blade forcing field,
        they can yield eta > 1.
        Checking this condition early avoids running the viscous solve,
        speeding up the solution process.

        Parameters
        ----------
        None

        Returns
        -------
        - valid : bool
            Boolean to indicate if a feasible result was found.
        """

        try:
            # Extract the efficiency from the forces output
            eta = self.forces_data_dict["data"]["EtaP"]
            # Return appropriate bool depending on found efficiency
            return 0. < eta < 1.
        except Exception:
            # Treat any exception as non-physical to skip viscous runs but keep
            # any batch analyses alive
            return False


    def GetEtaOutput(self) -> float:
        """
        Function to get the current efficiency.

        Parameters
        ----------
        None

        Returns
        -------
        - eta: float
            Efficiency
        """

        try:
            eta = self.forces_data_dict["data"]["EtaP"]
        except Exception:
            eta = 0.
        return eta


    def HandleExitFlag(self,
                       exit_flag: ExitFlag,
                       handle_type : str,
                       generate_output : bool = False,
                       output_type : OutputType = OutputType.FORCES_ONLY,
                       ) -> None:
        """
        Handle the exit flag of the solver execution.

        Parameters
        ----------
        - exit_flag : ExitFlag
            Exit flag indicating the status of the solver execution.
        - handle_type : str
            A string indicating the type of solve:
                - 'Inviscid'
                - 'Viscous'
        - generate_output: bool, optional
            A control boolean to determine if the outputs should be generated.
        - output_type: OutputType, optional
            An enum to determine which outputs to generate.
            OutputType.FORCES_ONLY generates only the forces data,
            while OutputType.ALL_FILES generates all files.

        Returns
        -------
        None
        """

        #If solver does not converge, call the non-convergence handler function.
        if exit_flag == ExitFlag.NON_CONVERGENCE:
            if handle_type == 'Inviscid':
                return
            if generate_output:
                self.WriteStateFile()
                self.HandleNonConvergence()

        # Else if the solver has crashed, restart MTSOL from the last saved
        # statefile IF the crash occurred during a viscous solve. Otherwise,
        # simply return.
        elif exit_flag == ExitFlag.CRASH:
            if handle_type == 'Inviscid':
                return
            else:
                self.GenerateProcess()
                return

        # Else if the solver has finished, update the statefile, and generate
        # the outputs
        elif exit_flag in (ExitFlag.COMPLETED, ExitFlag.SUCCESS,
                           ExitFlag.NOT_PERFORMED, ExitFlag.CHOKING):
            self.WriteStateFile()
            if generate_output:
                self.GenerateSolverOutput(output_type=output_type)
            else:
                self.GenerateSolverOutput(output_type=OutputType.FORCES_ONLY)
            return

        else:
            raise OSError(f"Unknown exit flag {exit_flag} encountered!") from None


    def TryExecuteViscousSolver(self,
                                surface_ID: list[int]|int = None,
                                ) -> ExitFlag:
        """
        Try to execute the MTSOL solver for the current analysis on the
        viscous surface surface_ID.

        Parameters
        ----------
        - surface_ID : list[int]|int, optional
            ID of the surface which is to be toggled. For a ducted fan,
            the ID should be either 1, 3, or 4.

        Returns
        -------
        - exit_flag : ExitFlag
            Exit flag indicating the status of the solver execution.
        """

        try:
            # Always kill and restart the process for a clean state
            if getattr(self, "process", None) and self.process.poll() is None:
                try:
                    self.process.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    self.process.kill()
                # Ensure the old reader thread is stopped
                # before starting a new process
                if getattr(self, "reader", None) and self.reader.is_alive():
                    if hasattr(self, "shutdown_event"):
                        self.shutdown_event.set()
                    try:
                        self.reader.join(timeout=10)
                    except Exception as e:
                        print(f"Error cleaning up reader thread: {e}")
            self.GenerateProcess()

            # Enter the modify menu and set the Reynolds number
            self.StdinWrite("m")
            self.WaitForCompletion(completion_type=CompletionType.PARAM_CHANGE)
            self.StdinWrite(f"R {self.operating_conditions['Inlet_Reynolds']}")
            self.WaitForCompletion(completion_type=CompletionType.PARAM_CHANGE)
            self.StdinWrite("")

            # Set viscous if surface_ID is given
            if surface_ID is not None:
                self.SetViscous(surface_ID, mode="enable")

            # Execute the solver and get the exit flag and iteration count
            exit_flag = self.ExecuteSolver(self.ITER_LIMIT_VISC)

            # If solve did not crash, update the statefile
            if exit_flag != ExitFlag.CRASH:
                self.WriteStateFile()

        except (OSError, BrokenPipeError):
            # If the solver crashes, set the exit flag to crash
            exit_flag = ExitFlag.CRASH

        return exit_flag


    def ConvergeIndividualSurfaces(self) -> ExitFlag:
        """
        Should a complete viscous analysis fail and cause an MTSOL crash,
        a partial run, where each axisymmetric surface is toggled individually,
        may sometimes improve performance and yield (partially)
        converged results.

        This function executes a consecutive partial run, where the centerbody,
        outer duct, and inner duct are converged in sequence.

        Parameters
        ----------
        None

        Returns
        -------
        - total_exit_flag : ExitFlag
            Exit flag indicating the overall status of the convergence.
        """

        # Define initial exit flags and iteration counters
        # Note that a negative iteration count indicates that the solver
        # did not run
        exit_flag_visc_CB = ExitFlag.NOT_PERFORMED
        exit_flag_visc_induct = ExitFlag.NOT_PERFORMED
        exit_flag_visc_outduct = ExitFlag.NOT_PERFORMED
        total_exit_flag = ExitFlag.NOT_PERFORMED

        # Execute the viscous solve for the centerbody
        exit_flag_visc_CB = self.TryExecuteViscousSolver(surface_ID=1)
        if exit_flag_visc_CB == ExitFlag.CRASH:
            # if the viscous solve caused a crash, return exit flag
            return exit_flag_visc_CB

        # Execute the viscous solve for the outside of the duct
        exit_flag_visc_outduct = self.TryExecuteViscousSolver(surface_ID=3)
        if exit_flag_visc_outduct == ExitFlag.CRASH:
            # if the viscous solve caused a crash, return appropriate exit flag
            return exit_flag_visc_outduct

        # Execute the final viscous solve for the inside of the duct
        exit_flag_visc_induct = self.TryExecuteViscousSolver(surface_ID=4)
        if exit_flag_visc_induct == ExitFlag.CRASH:
            # if the viscous solve caused a crash, return appropriate exit flag
            return exit_flag_visc_induct

        total_exit_flag = max([exit_flag_visc_CB,
                               exit_flag_visc_outduct,
                               exit_flag_visc_induct],
                               key=lambda flag: flag.value)

        return total_exit_flag


    def caller(self,
               run_viscous: bool = False,
               generate_output: bool = False,
               output_type: OutputType = OutputType.FORCES_ONLY,
               ) -> tuple[ExitFlag, dict[str, float]]:
        """
        Main execution interface of MTSOL.

        All executions of the MTSOL program are wrapped in
        try... except... finally... blocks to handle crashes of the solver

        Parameters
        ----------
        - run_viscous : bool, optional
            Flag to indicate whether to run a viscous solve. Default is False.
        - generate_output : bool, optional
            Flag to determine if MTFLOW outputs (forces, flowfield,
            boundary layer) should be generated.
        - output_type : OutputType, optional
            An enum to determine which output files to generate.
            OutputType.FORCES_ONLY generates only the forces data,
            while OutputType.ALL_FILES generates all files.

        Returns
        -------
        - A tuple containing:
            - total_exit_flag : ExitFlag
                Exit flag indicating the status of the solver execution. Is
                equal to the maximum value of the inviscid and viscous exit
                flags, since exit_flag > -1 indicate failed/nonconverging
                solves.
            - forces_data_dict : dict[str, float]
                A dictionary containing the integral flowfield variables from
                the forces output using the OutputProcessing class.
                If the full MTSOL output is requested, this is a copy of the
                relevant contents of the forces.analysis_name file.
        """

        # Define initial exit flags
        exit_flag_invisc = ExitFlag.NOT_PERFORMED
        exit_flag_visc = ExitFlag.NOT_PERFORMED

        try:
            # Generate MTSOL subprocess
            self.GenerateProcess()

            # Write operating conditions
            self.SetOperConditions()

            # Disable all viscous surfaces initially
            self.SetViscous([1, 3, 4], mode="disable")

            if generate_output:
                # Update the statefile with the operating conditions
                self.WriteStateFile()

            # Even if we don't want to generate output,
            # we still need to initialize an empty forces output to ensure
            # downstream handling does not fail
            self.forces_data_dict = self.output_processing_class.GetAllVariables()

            # Execute inviscid solve
            try:
                exit_flag_invisc = self.ExecuteSolver(self.ITER_LIMIT_INVISC)
            except (OSError, BrokenPipeError):
                # If the inviscid solve crashes, set the exit flag to crash
                exit_flag_invisc = ExitFlag.CRASH
            finally:
                # Handle solver based on exit flag
                # handle_type='Inviscid' bypasses the non-convergence loop.
                # This is intentional for a viscous run, as it speeds up the
                # solution process substantially. However, for an inviscid-only
                # run, we do need to perform this loop.
                exit_flag_handler = 'Inviscid' if run_viscous else 'Viscous'

                self.HandleExitFlag(exit_flag_invisc,
                                    handle_type=exit_flag_handler,
                                    generate_output=generate_output,
                                    output_type=output_type)
                total_exit_flag = exit_flag_invisc


            # Only run a viscous solve if required by the user
            # Theoretically there is the chance a viscous run may be started on
            # a non-converged inviscid solve. This is acceptable, as we assume a
            # steady-state residual case has formed at the end of the inviscid
            # case. There is a probability that by then running a viscous case,
            # convergence to the correct solution may still be obtained. Only
            # runs the viscous case if the exit flag is correct and if the
            # inviscid analysis was physical (i.e. has an efficiency < 100%)
            if run_viscous and \
                total_exit_flag in (ExitFlag.SUCCESS, ExitFlag.COMPLETED,
                                    ExitFlag.NON_CONVERGENCE) and \
                                        self.CheckInviscidOutput():
                # Get the inviscid efficiency
                eta_invisc = self.GetEtaOutput()

                # Toggle viscous on all surfaces
                self.ToggleViscous()  # Set the viscous Reynolds number
                self.SetViscous([1, 3, 4], mode="enable")

                # First we try to run a complete viscous case.
                # Only if this doesn't work and causes a crash do we try to
                # converge each surface individually
                try:
                    exit_flag_visc = self.ExecuteSolver(self.ITER_LIMIT_VISC)

                except (OSError, BrokenPipeError):
                    # Set the exit flag appropriately if crash occurred
                    exit_flag_visc = ExitFlag.CRASH

                finally:
                    # Try individual surfaces if the complete solve crashed
                    if exit_flag_visc == ExitFlag.CRASH:
                        exit_flag_visc = self.ConvergeIndividualSurfaces()

                    # Handle the exit flag
                    total_exit_flag = max([exit_flag_visc, exit_flag_invisc],
                                          key=lambda flag: flag.value)
                    self.HandleExitFlag(total_exit_flag,
                                        handle_type='Viscous',
                                        generate_output=generate_output,
                                        output_type=output_type)

                    # Check feasibility of the viscous efficiency. If not, set
                    # the exit flag to crash to enable appropriate downstream
                    # handling.
                    eta_visc = self.GetEtaOutput()
                    if eta_visc > eta_invisc:
                        total_exit_flag = ExitFlag.CRASH


            # Close MTSOL. If no output is generated, write an additional white
            # line to close MTSOL. Initial newline char is to ensure MTSOL
            # is in main menu.
            if self.process.poll() is None:
                self.StdinWrite("\n")
                self.StdinWrite("Q")
                if not generate_output:
                    self.StdinWrite("\n")

        finally:
            # Check that MTSOL has closed successfully.
            # If not, forcefully closes MTSOL
            if self.process.poll() is None:
                try:
                    self.process.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    self.process.kill()
            # Join reader thread if alive
            if getattr(self, "reader", None) and self.reader.is_alive():
                if hasattr(self, "shutdown_event"):
                    self.shutdown_event.set()
                self.reader.join(timeout=5)

        return total_exit_flag, self.forces_data_dict


if __name__ == "__main__":
    import time

    analysisName = "1031205207_4620_1a331d5f4aed"
    oper = {"Inlet_Mach": 0.125,
            "Inlet_Reynolds": 5112279,
            "N_crit": 9,
            }

    start_time = time.monotonic()
    test = MTSOL_call(oper, analysisName).caller(run_viscous=True,
                                                 generate_output=True)
    end_time = time.monotonic()

    print(f"Execution of MTSOL_call took {end_time -  start_time} seconds")